### ISSUE TITLE
Link to the documentation on napari-hub is dead

### ISSUE THREAD

**Issue by haesleinhuepf** [campaslab/napari-stress#228] opened 2023-01-23 16:59 UTC
The link to the documentation on the napari hub is not working (404). 

![image](https://user-images.githubusercontent.com/12660498/214101725-f1919380-2a73-4bf9-96f6-40158640f9af.png)

I propose updating this section:

https://github.com/campaslab/napari-stress/blob/4f29f84f12c6787c4f22b74fac55c65715a666f3/setup.cfg#L25-L29

and releasing napari-stress to pypi to fix this issue.

This should be fixed together with #205

**Comment by jo-mueller** [comment] 2023-01-24 07:43
Duplicate of #221? Should be fixed by PR #222

**Closed** 2023-01-31 09:15 UTC
