### ISSUE TITLE
Demo Analyze Everything Hung Up on Reconstruction 

### ISSUE THREAD

**Issue by carlos-gomez00** [campaslab/napari-stress#349] opened 2023-12-20 12:44 UTC
Issue in: docs/01_code_usage/01_toolboxes/demo_analyze_everything.ipynb

Protocol: (1) Ran Juypter-lab from Miniforge prompt; (2) Opened demo_analyze_everything.ipynb; (3) Edited Cell 3, 4, and 7; (4) Ran code

=> When reaching Cell 12, the code is hung up and causes napari to stop responding.

I have attached the messages from the terminal window. Not sure if this is a computer admin problem or an issue of the parameters I input into the code.

<img width="1088" alt="Console" src="https://github.com/campaslab/napari-stress/assets/102696383/ac08d451-23a3-408f-a347-c22316a30631">
<img width="1924" alt="Terminal" src="https://github.com/campaslab/napari-stress/assets/102696383/9000915a-d409-4a57-8501-c4adbb6509cd">

**Comment by carlos-gomez00** [comment] 2023-12-20 12:54
When Cell 12 stops and Cell 13 can be clicked following error is displayed:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[13], line 4
      1 _ = stress_backend.lbdv_info(Max_SPH_Deg=measurement_parameters['max_degree'],
      2                              Num_Quad_Pts=measurement_parameters['n_quadrature_points'])
----> 4 results_stress_analysis = measurements.comprehensive_analysis(results_reconstruction[2][0], **measurement_parameters,
      5                                                               verbose=verbose, use_dask=parallelize)

IndexError: list index out of range

**Comment by jo-mueller** [comment] 2023-12-20 14:17
Hi @carlos-gomez00 ,

this PR should fix the second one of your problems. As for the first one, the PR fixes the link to the dashboard that's created so that it also works for the viewer. 

The *root cause*, in this case, is probably that for some reasons (will have to look into the code), the reconstruction is sampling waaaay too dense on the surface of the droplet and then has to trace-refine a myriad of points, which is unnecessary. I can change the code to ensure that the density of points on the surface is calculated in physical units which should alleviate the problem a bit (but that's a separate PR).

**Comment by jo-mueller** [comment] 2023-12-21 17:23
@carlos-gomez00 I just looked into the data you were trying to analyze and found another issue: The `.tif` image you exported (presumably in Fiji) has the axes order `TZCYX` but common convention is `CTZYX` - the Matlab STRESS code probably would have complained about this, too. You can change the axes order in python with something like `image.transpose((2, 0, 1, 3, 4))` which fixes the order. Then, of course, you'd have to use only the channel with the droplet data for the analysis (e.g., `image[0]` after the reformatting).

If you do it from the viewer, this should be fine by default - checking why it was slow now.

**Comment by carlos-gomez00** [comment] 2023-12-22 12:16
Hey @jo-mueller I left the workstation running and it did finish running the code, but it had strange results. Probably due to the axes order, I'll try changing it and running it again. Just to show what it did, I pasted the results below. 

It finished the analysis
<img width="6274" alt="Code" src="https://github.com/campaslab/napari-stress/assets/102696383/3298f32e-688a-48f7-8be3-d27d85c7dc6e">

But the rescaled image did not overlap with the previous image 
<img width="1918" alt="Reconstruction" src="https://github.com/campaslab/napari-stress/assets/102696383/3e5440c1-2a33-41e2-9cf2-3468e16c2b8f">

I'll upload with the results after fixing axis on the data

**Comment by jo-mueller** [comment] 2023-12-22 12:24
@carlos-gomez00 

> But the rescaled image did not overlap with the previous image

This, at least, is something I'd expect. The input image doesn't show the correct physical pixel sizes, but the output does. You can fix it by passing the voxel sizes of the input data to the viewer in cell [9]:

```python
viewer.add_image(example_data, scale=[voxel_size_z, voxel_size_y, voxel_size_x])
```

**Comment by jo-mueller** [comment] 2024-04-08 09:15
Hi @carlos-gomez00 ,

can I close this issue?

**Comment by carlos-gomez00** [comment] 2024-04-11 11:47
Hi @jo-mueller 

I have tried to run the Notebook again and this is the error I obtained, the reconstruction didn't show this time

![Error_AnalyzeAll](https://github.com/campaslab/napari-stress/assets/102696383/1757f770-f4a6-4eaf-b996-908df86724c6)

I didn't understand the error as it was set to cubic

**Closed** 2024-04-11 12:27 UTC
